Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
	config.vm.box_version = "1.0.282"

	config.vm.define "madias-mS" do |control|
		control.vm.network _TEMP_, ip: "192.168.56.110"
		control.vm.hostname = "madias-mS"
		control.vm.provider _TEMP_ do |v|
			v.customize ["modifyvm", :id, "--name", "madias-mS"]
		end
		
	end
end 

