Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
	config.vm.box_version = "1.0.282"
	config.vm.network "madias-net", guest: 80, host: 8080

	config.vm.define "madias-mS" do |server|
		server.vm.network "madias-net", ip: "192.168.56.110"
		server.vm.hostname = "madias-mS"
		server.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "madias-mS"]
			#v.vmx["memsize"] = "512"
			#v.vmx["numvcpus"] = "1"
		end
		#server.vm.provision "shell", :inline "echo MADIAS-mS"
		
	end
	
	config.vm.define "madias-mSW" do |worker|
		worker.vm.network "madias-net", ip: "192.168.56.111"
		worker.vm.hostname = "madias-mSW"
		worker.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "madias-mSW"]
			#v.vmx["memsize"] = "512"
			#v.vmx["numvcpus"] = "1"
		end
		#worker.vm.provision "shell", :inline "echo MADIAS-mSW"
	end

end 

