Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"
	config.vm.box_version = "1.0.282"
	config.vm.network "madias-net", guest: 80, host: 8080

	config.vm.define "madias-mS" do |control|
		control.vm.network "madias-net", ip: "192.168.56.110"
		control.vm.hostname = "madias-mS"
		control.vm.provider "vmware_fusion" do |v|
			v.customize ["modifyvm", :id, "--name", "madias-mS"]
		end
		control.vm.provision "shell", :inline "echo MADIAS-mS"
		
	end
	
	config.vm.define "madias-mSW" do |control|
		control.vm.network "madias-net", ip: "192.168.56.111"
		control.vm.hostname = "madias-mSW"
		control.vm.provider "vmware_fusion" do |v|
			v.customize ["modifyvm", :id, "--name", "madias-mSW"]
		end
		control.vm.provision "shell", :inline "echo MADIAS-mSW"
	end

end 

